title: Misc Notes
# description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://simpleshue.github.io/misc

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

baseurl: /misc


search.heading_level: 6
# Show navigation error report
nav_error_report: true # default is false/nil.

permalink: pretty


defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
    values:
      layout: "default"


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/simpleshue/misc" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

math: mathjax