title: Misc Notes
# description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://simpleshue.github.io/misc

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

baseurl: /misc


search.heading_level: 6

back_to_top: true
back_to_top_text: "Back to top"